### ISSUE TITLE
flask redirects result in 200 instead of 302

### ISSUE THREAD

**Issue by rmahoney-bl** [Miserlou/flask-zappa#10]
normally I would do:

``` python
return flask.redirect(url)
```

I can see when I test the gateway resource that it is trying to send the 302 header... but I think that since it is a successful request is gets rewritten to a 200.

For now, I have resorted to this hack just to get my app to work as expected:

``` python
response = '''<html>
    <head><script>window.location='{uri}'</script></head>
    <body>Redirecting to <a href="{uri}">{uri}</a></body>
</html>'''.replace('{uri}', uri)
return response, 200
```

**Comment by Miserlou** [comment]
flask-zappa is a dead project!

Please just use the upstream Zappa client instead, as all of the functionality and more is already there.

If you have this same problem, please re-open a ticket upstream.
