### ISSUE TITLE
Docs Appear Copied from django-zappa

### ISSUE THREAD

**Issue by cancan101** [Miserlou/flask-zappa#2]
The section on [`ZAPPA_SETTINGS` ](https://github.com/Miserlou/flask-zappa#configuration) appears to be copied from the django-zappa and does not appear relevant for flask.

**Comment by Doerge** [comment]
That is correct. There is no stable flask-zappa yet.

There is a (quite unstable) branch [here](https://github.com/Miserlou/flask-zappa/tree/basic_example) which is under development. The usage is described in [these comments.](https://github.com/Miserlou/flask-zappa/issues/1)

I will update the readme on that branch right away.
